name: Build & Deploy Beratung

on:
  push:
    paths:
    - 'beratung/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-vuepress
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: |
        cd beratung
        npx vuepress build
      env:
        CI: true
    - name: Deploy
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOYER }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.SERVER_PORT }}
        FOLDER: "./beratung/.vuepress/dist/*"
        SERVER_IP: ${{ secrets.SERVER_IP }}
        USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_DESTINATION: ${{ secrets.SERVER_DEST }}/beratung
