name: Build & Deploy Physio
permissions:
   contents: write

on:
  push:
    paths:
    - 'physio/**'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-vuepress
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Build
      run: |
        cd physio
        npm ci
        npm run build
      env:
        CI: true
    - name: GIT commit and push all changed files
      run: |
        git config --global user.name "Liedtke"
        git config --global user.email "liedtke@physio-oranienburg.de"
        git commit -a -m "feat: apply changes"
        git push
        git subtree push --prefix .vuepress/dist origin physio
